import type {Metadata} from "next";
import {isOwnerAuthenticated} from "../../lib/owner-auth";
import {getCityDay,getCityStaff,getClientForBooking,getClients,getOwnerServices} from "../../lib/clinic-admin";
import {addCityBeautician,addOwnerService,createCityAppointment,importOwnerClients,importOwnerServices,ownerLogin,ownerLogout,settleCityAppointment} from "./actions";
import "./owner.css";

export const dynamic="force-dynamic";
export const metadata:Metadata={title:"VenuX Owner · City Operations",robots:{index:false,follow:false}};
const todaySydney=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Australia/Sydney",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const times=["9:00 AM","9:30 AM","10:00 AM","10:30 AM","11:00 AM","11:30 AM","12:00 PM","12:30 PM","1:00 PM","1:30 PM","2:00 PM","2:30 PM","3:00 PM","3:30 PM","4:00 PM","4:30 PM","5:00 PM","5:30 PM","6:00 PM"];

function OwnerLogin({error}:{error?:string}){return <main className="owner-login"><section><div className="owner-mark">✦ VenuX</div><p>Private owner access</p><h1>City operations.</h1><form action={ownerLogin}><label>Owner password<input name="password" type="password" autoComplete="current-password" required autoFocus/></label><button>Sign in securely</button></form>{error?<div className="owner-alert error">Password was not accepted or the owner session expired.</div>:null}<small>This URL uses a separate owner-only session. Customer, staff and revenue information is private.</small></section></main>}

export default async function OwnerPage({searchParams}:{searchParams:Promise<{date?:string;q?:string;client?:string;error?:string;service?:string;imported?:string;clientsImported?:string;clientsProcessed?:string;clientDuplicates?:string;staff?:string;booked?:string;settled?:string}>}){
  const params=await searchParams;if(!(await isOwnerAuthenticated()))return <OwnerLogin error={params.error}/>;
  const date=/^\d{4}-\d{2}-\d{2}$/.test(params.date??"")?String(params.date):todaySydney(),clientId=Number(params.client??0);
  const [services,staff,day,selectedClient,searchResults]=await Promise.all([getOwnerServices(),getCityStaff(),getCityDay(date),clientId>0?getClientForBooking(clientId):null,params.q?getClients(params.q):Promise.resolve([])]);
  const activeServices=services.filter(row=>row.active);
  const totalMinutes=day.settlement.reduce((sum,row)=>sum+Number(row.minutes??0),0),totalRevenue=day.settlement.reduce((sum,row)=>sum+Number(row.revenue??0),0);
  return <main className="owner-app"><header className="owner-top"><a href="/owner"><span>✦</span><strong>VenuX Owner</strong><small>City · 515 Kent Street</small></a><nav><a href="#booking">Book</a><a href="#schedule">Day schedule</a><a href="#services">Projects</a><a href="#team">Team</a></nav><form action={ownerLogout}><button>Sign out</button></form></header><div className="owner-main">
    <header className="owner-heading"><div><p>Owner-only City system</p><h1>Daily operations.</h1></div><form method="get"><label>Working date<input type="date" name="date" defaultValue={date}/></label><button>Open day</button></form></header>
    {params.service?<div className="owner-alert">Project saved.</div>:null}{params.imported?<div className="owner-alert">Imported {params.imported} projects.</div>:null}{params.clientsImported!==undefined?<div className="owner-alert">Client import complete: {params.clientsProcessed} valid records processed, {params.clientsImported} new clients added{Number(params.clientDuplicates)>0?`, ${params.clientDuplicates} exact duplicates combined`:""}.</div>:null}{params.staff?<div className="owner-alert">City beautician added.</div>:null}{params.booked?<div className="owner-alert">Appointment added to the selected beautician’s schedule.</div>:null}{params.settled?<div className="owner-alert">Daily appointment settlement updated.</div>:null}{params.error?<div className="owner-alert error">{params.error==="conflict"?"This beautician already has an appointment at that time.":params.error==="client-columns"?"The client file needs Name and Mobile columns.":params.error==="clients"?"Please upload the prepared client CSV file.":"Please check the submitted information."}</div>:null}

    <section className="owner-metrics"><article><small>City appointments</small><strong>{day.appointments.length}</strong><span>{new Date(`${date}T00:00:00`).toLocaleDateString("en-AU",{weekday:"long",day:"numeric",month:"long"})}</span></article><article><small>Scheduled project time</small><strong>{Math.floor(totalMinutes/60)}h {totalMinutes%60}m</strong><span>Excludes cancelled and no-show</span></article><article><small>Completed revenue</small><strong>${totalRevenue.toLocaleString("en-AU")}</strong><span>Only completed appointments</span></article><article><small>City beauticians</small><strong>{staff.length}/3</strong><span>First three active City team members</span></article></section>

    <section className="owner-panel" id="booking"><header><div><small>01 · Client booking</small><h2>Book a City client</h2></div></header><form action={importOwnerClients} className="owner-import-form"><div><strong>Import client records</strong><small>Prepared CSV columns: Group, Name, DOB, Mobile, Email, Address · existing clients are matched automatically</small></div><input name="clientFile" type="file" accept=".csv,text/csv" required/><button>Import clients</button></form><div className="owner-client-search"><form method="get"><input type="hidden" name="date" value={date}/><label>Search mobile, client name or email<input name="q" defaultValue={params.q??""} placeholder="04XX XXX XXX"/></label><button>Find client</button></form>{params.q?<div className="owner-search-results">{searchResults.length?searchResults.slice(0,8).map(client=><a href={`/owner?date=${date}&client=${client.id}#booking`} key={String(client.id)}><strong>{String(client.full_name)}</strong><span>{String(client.mobile)} · {client.email?String(client.email):"No email"}</span><small>{Number(client.visit_count)} appointments</small></a>):<p>No match. Enter a new client below.</p>}</div>:null}</div>
      {selectedClient?<div className="owner-selected"><span>Selected client</span><strong>{String(selectedClient.full_name)}</strong><small>{String(selectedClient.mobile)} · {Number(selectedClient.visit_count)} appointments</small></div>:null}
      <form action={createCityAppointment} className="owner-booking-form">{selectedClient?<input type="hidden" name="clientId" value={String(selectedClient.id)}/>:null}<input type="hidden" name="date" value={date}/><label>Client name<input name="name" required defaultValue={selectedClient?String(selectedClient.full_name):""}/></label><label>Mobile<input name="mobile" required inputMode="tel" defaultValue={selectedClient?String(selectedClient.mobile):""}/></label><label>Email<input name="email" type="email" defaultValue={selectedClient?String(selectedClient.email):""}/></label><label>Project<select name="serviceId" required defaultValue=""><option value="" disabled>Select project</option>{activeServices.map(service=><option value={String(service.id)} key={String(service.id)}>{String(service.service_name)} · {Number(service.duration_minutes)} min · ${Number(service.regular_price)}</option>)}</select></label><label>Beautician<select name="staffId" required defaultValue=""><option value="" disabled>Select beautician</option>{staff.map(person=><option value={String(person.id)} key={String(person.id)}>{String(person.full_name)}</option>)}</select></label><label>Time<select name="time" required defaultValue=""><option value="" disabled>Select time</option>{times.map(time=><option key={time}>{time}</option>)}</select></label><label className="wide">Notes<textarea name="notes"/></label><label className="owner-check"><input type="checkbox" name="serviceSmsConsent" value="yes" defaultChecked={Boolean(selectedClient?.service_sms_consent)}/> Client agreed to appointment confirmation by SMS</label><button disabled={!staff.length||!activeServices.length}>Add to City schedule</button></form>
    </section>

    <section className="owner-panel" id="schedule"><header><div><small>02 · Schedule & settlement</small><h2>Three-beautician day board</h2></div><span>Update status and final charge at close of day</span></header><div className="beautician-board">{staff.map(person=>{const appointments=day.appointments.filter(row=>Number(row.staff_id)===Number(person.id));const settlement=day.settlement.find(row=>String(row.staff_name)===String(person.full_name));return <article key={String(person.id)}><header><div><strong>{String(person.full_name)}</strong><small>{String(person.role)}</small></div><span>{Number(settlement?.minutes??0)} min</span></header>{appointments.length?appointments.map(row=><div className="city-slot" key={String(row.id)}><time>{String(row.requested_time)}</time><div><strong>{String(row.full_name)}</strong><span>{String(row.treatment)} · {Number(row.duration_minutes)} min</span><small>{String(row.mobile)}</small></div><form action={settleCityAppointment}><input type="hidden" name="id" value={String(row.id)}/><input type="hidden" name="date" value={date}/><input type="hidden" name="staffId" value={String(person.id)}/><select name="status" defaultValue={String(row.status)} aria-label={`Status for ${row.full_name}`}><option value="requested">Requested</option><option value="confirmed">Confirmed</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option><option value="no_show">No-show</option></select><label>$<input name="amount" type="number" min="0" defaultValue={Number(row.total_amount||row.regular_price||0)} aria-label={`Final amount for ${row.full_name}`}/></label><button>Settle</button></form></div>):<p className="owner-empty">No appointments for this beautician.</p>}<footer><span>{Number(settlement?.projects??0)} projects · {Number(settlement?.minutes??0)} minutes</span><strong>${Number(settlement?.revenue??0).toLocaleString("en-AU")}</strong></footer></article>})}{staff.length<3?<div className="owner-empty-board">Add {3-staff.length} more City beautician{3-staff.length===1?"":"s"} below to complete the three-column schedule.</div>:null}</div></section>

    <section className="owner-bottom"><div className="owner-panel" id="services"><header><div><small>03 · Project catalogue</small><h2>Add or import projects</h2></div><span>{activeServices.length} active</span></header><form action={addOwnerService} className="owner-service-form"><label>Project name<input name="name" required/></label><label>Category<input name="category" defaultValue="Skin"/></label><label>Minutes<input name="duration" type="number" min="5" max="480" step="5" required/></label><label>Regular price<input name="price" type="number" min="0" step="1" required/></label><button>Add project</button></form><form action={importOwnerServices} className="owner-import-form"><div><strong>Import CSV project list</strong><small>Columns: Name, Category, Duration, Price · up to 500 rows</small></div><input name="serviceFile" type="file" accept=".csv,text/csv" required/><button>Import</button></form><div className="service-list">{activeServices.slice(0,30).map(service=><div key={String(service.id)}><strong>{String(service.service_name)}</strong><span>{String(service.category)}</span><span>{Number(service.duration_minutes)} min</span><b>${Number(service.regular_price)}</b></div>)}</div></div>
      <div className="owner-panel" id="team"><header><div><small>04 · City team</small><h2>Three beauticians</h2></div></header><form action={addCityBeautician} className="owner-team-form"><label>Name<input name="name" required/></label><label>Role<select name="role" defaultValue="Beauty therapist"><option>Beauty therapist</option><option>Dermal therapist</option><option>Nurse</option><option>Manager</option></select></label><button>Add to City team</button></form><div className="owner-team-list">{staff.map((person,index)=><div key={String(person.id)}><b>0{index+1}</b><span><strong>{String(person.full_name)}</strong><small>{String(person.role)}</small></span></div>)}</div><p className="owner-note">The City schedule displays the first three active City team members. Each beautician can hold a separate appointment at the same time.</p></div></section>
  </div></main>;
}
