import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { isAdminAuthenticated } from "../../../../lib/admin-auth";
import { getClientClinicalRecord } from "../../../../lib/clinic-admin";
import { AdminLogin,AdminShell,statusLabel } from "../../admin-ui";
import { addClientCourseAction,addSkinAssessmentAction,addTreatmentRecordAction,changeMembership,completeFollowupAction,updateClientProfileAction,updateHealthProfileAction,useClientCourseSessionAction } from "../../actions";
import "../../admin.css";
import "./clinical.css";
import "./session.css";

export const dynamic="force-dynamic";
export const metadata:Metadata={title:"Clinical record | VenuX Clinic OS",robots:{index:false,follow:false}};
const value=(input:unknown)=>input==null?"":String(input);
const dateValue=(input:unknown)=>input?new Date(String(input)).toISOString().slice(0,10):"";
const dateTimeValue=(input:unknown)=>input?new Date(String(input)).toLocaleString("en-AU",{dateStyle:"medium",timeStyle:"short"}):"";

export default async function ClientRecord({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{saved?:string;error?:string}>}){
  const query=await searchParams;
  if(!(await isAdminAuthenticated()))return <AdminLogin error={query.error}/>;
  const clientId=Number((await params).id);if(!Number.isInteger(clientId)||clientId<=0)notFound();
  const record=await getClientClinicalRecord(clientId);if(!record.client)notFound();
  const c=record.client,h=record.health??{};
  return <AdminShell active="Clients & membership">
    <header className="clinic-admin-head clinical-head"><div><p>Private clinical record · VX{String(clientId).padStart(6,"0")}</p><h1>{value(c.full_name)}</h1></div><div className="record-actions"><a href={`tel:${value(c.mobile)}`}>Call</a><a href={`https://wa.me/${value(c.mobile).replace(/^0/,"61").replace(/\D/g,"")}`} target="_blank" rel="noreferrer">WhatsApp</a><a href="/admin/clients">← Clients</a></div></header>
    {query.saved?<div className="clinic-alert">Saved securely. The change has been added to the audit history.</div>:null}
    {query.error?<div className="clinic-alert error">Please review the required fields and values.</div>:null}
    <nav className="record-tabs"><a href="#profile">Profile</a><a href="#membership">Membership</a><a href="#health">Health</a><a href="#assessment">Assessment</a><a href="#treatments">Treatments</a><a href="#followups">Follow-ups</a><a href="#courses">Courses</a><a href="#history">Audit</a></nav>

    <section id="profile" className="clinical-section"><header><div><span>01</span><h2>Client profile</h2></div><p>Contact, identity and emergency details.</p></header><form action={updateClientProfileAction} className="clinical-form"><input type="hidden" name="clientId" value={clientId}/><label>Full name<input name="fullName" defaultValue={value(c.full_name)} required/></label><label>Mobile<input name="mobile" defaultValue={value(c.mobile)} required/></label><label>Email<input name="email" type="email" defaultValue={value(c.email)}/></label><label>Date of birth<input name="dob" type="date" defaultValue={dateValue(c.dob)}/></label><label>Gender<input name="gender" defaultValue={value(c.gender)}/></label><label>Occupation<input name="occupation" defaultValue={value(c.occupation)}/></label><label className="wide">Address<input name="address" defaultValue={value(c.address)}/></label><label>Emergency contact<input name="emergencyName" defaultValue={value(c.emergency_contact_name)}/></label><label>Emergency phone<input name="emergencyPhone" defaultValue={value(c.emergency_contact_phone)}/></label><label>Client source<select name="leadSource" defaultValue={value(c.lead_source)}><option value="">Select source</option><option>Google</option><option>Instagram</option><option>RED / Xiaohongshu</option><option>Friend referral</option><option>Walk-in</option><option>Other</option></select></label><button type="submit">Save profile</button></form></section>

    <section id="membership" className="clinical-section"><header><div><span>02</span><h2>Membership card & price</h2></div><p>Activate the card and record the paid price or recharge amount.</p></header><form action={changeMembership} className="clinical-form compact"><input type="hidden" name="clientId" value={clientId}/><input type="hidden" name="returnTo" value="record"/><label>Membership status<select name="status" defaultValue={value(c.membership_status)||"inactive"}><option value="inactive">Inactive</option><option value="active">Active</option><option value="paused">Paused</option></select></label><label>Card balance (AUD)<input name="balance" type="number" min="0" step="0.01" defaultValue={Number(c.balance??0)}/></label><label>Membership price / paid (AUD)<input name="amountPaid" type="number" min="0" step="0.01" defaultValue={Number(c.membership_amount_paid??0)}/></label><button>Save membership card</button></form></section>

    <section id="health" className="clinical-section sensitive"><header><div><span>02</span><h2>Health & contraindications</h2></div><p>Restricted health information. Confirm directly with the client before treatment.</p></header><form action={updateHealthProfileAction} className="clinical-form"><input type="hidden" name="clientId" value={clientId}/><label>Skin type<input name="skinType" defaultValue={value(h.skin_type)} placeholder="Dry, oily, combination, sensitive…"/></label><label>Pregnancy status<input name="pregnancyStatus" defaultValue={value(h.pregnancy_status)} placeholder="Not applicable / No / Yes / Unsure"/></label><label className="wide">Primary skin concerns<textarea name="primaryConcerns" defaultValue={value(h.primary_concerns)}/></label><label className="wide">Allergies<textarea name="allergies" defaultValue={value(h.allergies)} placeholder="Record none known when confirmed"/></label><label className="wide">Medical conditions<textarea name="medicalConditions" defaultValue={value(h.medical_conditions)}/></label><label className="wide">Current medications<textarea name="medications" defaultValue={value(h.medications)}/></label><label>Breastfeeding<select name="breastfeeding" defaultValue={h.breastfeeding?"yes":"no"}><option value="no">No</option><option value="yes">Yes</option></select></label><label>Implants / devices<input name="implants" defaultValue={value(h.implants)}/></label><label className="wide">Previous aesthetic treatments<textarea name="aestheticHistory" defaultValue={value(h.aesthetic_history)}/></label><label className="wide">Current skincare products<textarea name="currentSkincare" defaultValue={value(h.current_skincare)}/></label><button type="submit">Save health profile</button></form></section>

    <section id="assessment" className="clinical-section"><header><div><span>03</span><h2>Consultation & skin assessment</h2></div><p>Document clinical reasoning, goals and agreed plan.</p></header><form action={addSkinAssessmentAction} className="clinical-form compact"><input type="hidden" name="clientId" value={clientId}/><label>Concern categories<input name="concerns" placeholder="Acne, sensitivity, pigment, laxity…"/></label><label>Main concern<input name="mainConcern"/></label><label>Anxiety / concern level<select name="anxietyLevel" defaultValue=""><option value="">Not recorded</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} / 5</option>)}</select></label><label>Fitzpatrick type<select name="fitzpatrick" defaultValue=""><option value="">Not assessed</option>{[1,2,3,4,5,6].map(n=><option key={n} value={n}>Type {n}</option>)}</select></label><label className="wide">Expected outcome<textarea name="expectedOutcome"/></label><label className="wide">Treatment recommendation<textarea name="recommendation"/></label><label className="wide">Course plan<textarea name="coursePlan"/></label><label>Budget (AUD)<input name="budget" type="number" min="0"/></label><label>Assessed by<input name="assessedBy" required/></label><label className="wide">Practitioner notes<textarea name="notes"/></label><button type="submit">Add assessment</button></form><div className="record-list">{record.assessments.map(a=><article key={value(a.id)}><header><strong>{value(a.main_concern)||"Skin assessment"}</strong><time>{dateTimeValue(a.created_at)}</time></header><p>{value(a.treatment_recommendation)||"No recommendation recorded."}</p><small>Fitzpatrick {value(a.fitzpatrick)||"—"} · By {value(a.assessed_by)}</small></article>)}</div></section>

    <section id="treatments" className="clinical-section"><header><div><span>04</span><h2>Treatment records</h2></div><p>Product traceability, device parameters, response and operator sign-off.</p></header><form action={addTreatmentRecordAction} className="clinical-form"><input type="hidden" name="clientId" value={clientId}/><label>Service<input name="service" required/></label><label>Date & time<input name="treatedAt" type="datetime-local" required/></label><label>Operator<input name="operator" required/></label><label>Treatment area<input name="area"/></label><label>Products used<input name="products"/></label><label>Brand<input name="brand"/></label><label>Batch number<input name="batchNumber"/></label><label>Dose / amount<input name="dosage"/></label><label className="wide">Device parameters<textarea name="parameters" placeholder="Mode, depth, energy, passes, cooling…"/></label><label>Shots / lines<input name="shotCount" type="number" min="0"/></label><label>Units<input name="unitCount" type="number" min="0" step="1"/></label><label className="wide">Injection points / treatment map<textarea name="treatmentMap"/></label><label className="wide">Immediate skin response<textarea name="immediateResponse"/></label><label className="wide">Adverse reaction<textarea name="adverseReaction"/></label><label className="wide">Management provided<textarea name="adverseManagement"/></label><label className="wide signature">Operator signature <input name="signature" placeholder="Type full legal name to sign" required/><small>Submitting records the signed name and timestamp in the audit trail.</small></label><button type="submit">Sign & save treatment</button></form><div className="record-list">{record.treatments.map(t=><article key={value(t.id)}><header><strong>{value(t.service)}</strong><time>{dateTimeValue(t.treated_at)}</time></header><p>{value(t.treatment_area)}{t.brand?` · ${value(t.brand)}`:""}{t.batch_number?` · Batch ${value(t.batch_number)}`:""}</p><small>Operator: {value(t.operator_name)} · Signed: {value(t.operator_signature)}</small></article>)}</div></section>

    <section id="followups" className="clinical-section"><header><div><span>05</span><h2>Follow-up</h2></div><p>IPL, pico, skin booster, anti-wrinkle and HIFU records create recommended follow-up tasks automatically.</p></header><div className="followup-list">{record.followups.length?record.followups.map(f=><form action={completeFollowupAction} key={value(f.id)} className={value(f.status)==="completed"?"complete":""}><input type="hidden" name="clientId" value={clientId}/><input type="hidden" name="followupId" value={value(f.id)}/><header><div><strong>{value(f.followup_type)}</strong><span className={`status-pill ${value(f.status)}`}>{statusLabel(f.status)}</span></div><time>Due {dateValue(f.due_date)}</time></header>{value(f.status)==="pending"?<><label>Recovery & client feedback<textarea name="notes"/></label><div className="followup-fields"><label>Satisfaction<select name="satisfaction" defaultValue=""><option value="">Not scored</option>{[1,2,3,4,5].map(n=><option value={n} key={n}>{n} / 5</option>)}</select></label><label><input type="checkbox" name="abnormal" value="yes"/> Abnormal reaction</label><label><input type="checkbox" name="reviewRequired" value="yes"/> Practitioner review needed</label></div><button>Complete follow-up</button></>:<p>{value(f.recovery_notes)||"Completed without notes."}</p>}</form>):<div className="empty-admin">No follow-ups yet. Supported treatments create tasks when a treatment record is saved.</div>}</div></section>

    <section id="courses" className="clinical-section"><header><div><span>06</span><h2>Courses & packages</h2></div><p>Track purchased, used and remaining sessions with expiry.</p></header><form action={addClientCourseAction} className="clinical-form compact"><input type="hidden" name="clientId" value={clientId}/><label>Course / package<input name="name" required/></label><label>Purchased sessions<input name="purchased" type="number" min="1" required/></label><label>Used sessions<input name="used" type="number" min="0" defaultValue="0" required/></label><label>Expiry date<input name="expiresOn" type="date"/></label><label>Amount paid (AUD)<input name="amountPaid" type="number" min="0" required/></label><label>Status<select name="status"><option value="active">Active</option><option value="completed">Completed</option><option value="expired">Expired</option></select></label><button>Add course</button></form><div className="course-grid">{record.courses.map(p=><article key={value(p.id)}><span className={`status-pill ${value(p.status)}`}>{statusLabel(p.status)}</span><strong>{value(p.course_name)}</strong><b>{Math.max(0,Number(p.purchased_sessions)-Number(p.used_sessions))} sessions remaining</b><small>{value(p.used_sessions)} used of {value(p.purchased_sessions)} · Paid ${Number(p.amount_paid??0).toLocaleString("en-AU")} · Expires {dateValue(p.expires_on)||"not set"}</small>{value(p.status)==="active"&&Number(p.used_sessions)<Number(p.purchased_sessions)?<form action={useClientCourseSessionAction} className="session-use-form"><input type="hidden" name="clientId" value={clientId}/><input type="hidden" name="courseId" value={value(p.id)}/><button>Use 1 session</button></form>:null}</article>)}</div></section>

    <section id="history" className="clinical-section"><header><div><span>07</span><h2>Access & change history</h2></div><p>Initial audit trail. Individual staff accounts and role-based permissions are the next security step.</p></header><div className="audit-list">{record.audits.map(a=><div key={value(a.id)}><time>{dateTimeValue(a.created_at)}</time><strong>{value(a.actor_name)} · {value(a.action)}</strong><span>{value(a.detail)}</span></div>)}</div></section>
  </AdminShell>;
}
