import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Footer, Header } from "../../site-chrome";
import "./treatment-detail.css";

const treatments = {
  "facial-treatments": { title:"Facial", italic:"treatments.", kicker:"Skin · Professional facials", intro:"Personalised professional facials selected for your skin condition, concerns and treatment goals.", principle:"Professional facial protocols combine skin assessment, cleansing, exfoliation and selected treatment products or devices. The exact facial is chosen after considering sensitivity, barrier condition and your current routine.", concerns:["Hydration and glow","Congestion and breakouts","Sensitivity and barrier support"], before:"Tell us about allergies, medications, active skin conditions, recent procedures and the products you currently use.", during:"Your practitioner selects the appropriate professional protocol, products and optional enhancements for your skin.", after:"You receive relevant home-care and sun-protection advice. Temporary redness or sensitivity can vary by treatment." },
  "laser-facial": { title:"CO₂ Laser", italic:"resurfacing.", kicker:"Skin · Ablative laser", intro:"A consultation-led CO₂ laser resurfacing pathway for appropriate texture, scarring and photo-ageing concerns.", principle:"CO₂ laser uses an ablative wavelength to create controlled treatment zones in the skin. Treatment depth, coverage and settings depend on the device, treatment area, skin assessment and clinical suitability.", concerns:["Texture and selected scarring","Photo-ageing appearance","Resurfacing consultation"], before:"A qualified practitioner must assess your medical history, skin type, medications, healing history, infection risk and recent procedures. Preparation requirements vary.", during:"Protective eyewear and an appropriate comfort plan are used. Treatment settings and time depend on the area and prescribed treatment depth.", after:"Redness, swelling, sensitivity, crusting and downtime may occur. Follow wound-care, infection-prevention and strict sun-protection instructions provided by your practitioner." },
  "dmk-enzyme-therapy": { title:"DMK Enzyme", italic:"therapy.", kicker:"Skin · Enzyme therapy", intro:"A structured professional skin revision treatment selected after assessing your skin, goals and current routine.", principle:"DMK Enzyme Therapy uses professional formulations and a characteristic setting mask within an individually planned skin revision pathway.", concerns:["Congestion and imbalance","Barrier and skin function","Texture and appearance"], before:"Your practitioner reviews current products, sensitivities and active skin conditions before selecting a level.", during:"Professional products are layered before the enzyme mask sets firmly on the skin.", after:"Home care and timing of future treatments are discussed according to your individual response." },
  "led-light-therapy": { title:"LED Light", italic:"therapy.", kicker:"Skin · Light therapy", intro:"A non-invasive light treatment that may be used alone or alongside selected professional facial treatments.", principle:"LED devices emit selected wavelengths of low-level light. The wavelength, duration and treatment plan are chosen for the intended professional protocol.", concerns:["Post-treatment support","Red or reactive appearance","Maintenance care"], before:"Skin is assessed and eye protection is provided. Photosensitising medication must be disclosed.", during:"You rest beneath the LED device while the selected light programme runs.", after:"There is generally minimal interruption to daily activities, although individual responses vary." },
  "hifu-ultherapy": { title:"HIFU &", italic:"Ultherapy.", kicker:"Methods · Ultrasound", intro:"Consultation-led focused ultrasound treatment planning for appropriate lifting and firmness concerns.", principle:"Focused ultrasound delivers energy at selected depths beneath the skin surface. Treatment planning depends on anatomy, device, area and suitability.", concerns:["Laxity appearance","Jawline definition goals","Non-surgical consultation"], before:"A qualified practitioner reviews anatomy, medical history, expectations and whether treatment is appropriate.", during:"Treatment sensations vary by area and energy level. The practitioner follows an individual treatment map.", after:"Temporary tenderness, redness or swelling may occur. Results and recovery vary between individuals." },
  "rf-microneedling": { title:"RF", italic:"microneedling.", kicker:"Methods · Radiofrequency", intro:"A professional procedure combining controlled microneedling with radiofrequency energy for suitable skin concerns.", principle:"Insulated or non-insulated microneedles create controlled channels while radiofrequency energy is delivered at selected depths.", concerns:["Texture and pores","Selected acne-scar concerns","Firmness appearance"], before:"Suitability, infection risk, medications, healing history and treatment area are assessed first.", during:"Topical anaesthetic may be used. Settings and depth are selected for the treatment area and goal.", after:"Redness, swelling and sensitivity can occur. Follow infection-prevention and sun-protection advice carefully." },
  "skin-booster": { title:"Skin Booster", italic:"consultation.", kicker:"Aesthetics · Skin quality", intro:"A consultation pathway for clients interested in professional skin-quality and hydration options.", principle:"Skin booster is a broad marketing term and may refer to different products or procedures. The exact product, practitioner, risks, expected benefit and cost must be confirmed in consultation.", concerns:["Hydration goals","Skin-quality concerns","Personalised aesthetic planning"], before:"Medical history, allergies, medications, pregnancy status and treatment expectations require assessment.", during:"The precise procedure depends on the legally supplied product and the qualified treating practitioner.", after:"Recovery, risks and aftercare vary by procedure. You will receive product-specific information before consenting." },
} as const;

type Slug = keyof typeof treatments;
export function generateStaticParams(){ return Object.keys(treatments).map(slug=>({slug})); }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{ const {slug}=await params; const item=treatments[slug as Slug]; return item?{title:`${item.title} | VenuX Skin Clinic`,description:item.intro}:{}; }

export default async function TreatmentDetail({params}:{params:Promise<{slug:string}>}){ const {slug}=await params; const item=treatments[slug as Slug]; if(!item) notFound(); return <main><Header />
  <section className="detail-hero"><div><a className="back-link" href="/treatments">← All treatments</a><p className="kicker">{item.kicker}</p><h1>{item.title}<br/><i>{item.italic}</i></h1><p>{item.intro}</p><div className="hero-actions"><a className="button dark" href="/book">Book a consultation</a><a className="text-link" href="#details">Learn more ↓</a></div></div><div className="detail-orbit" aria-hidden="true"><i/><i/><span>V</span></div></section>
  <nav className="detail-nav"><a href="#principle">01 · Principle</a><a href="#concerns">02 · Concerns</a><a href="#appointment">03 · Appointment</a><a href="#questions">04 · Questions</a></nav>
  <section className="detail-principle" id="principle"><div><p className="kicker">01 · How it works</p><h2>Professional<br/><i>principle.</i></h2></div><p>{item.principle}</p></section>
  <section className="detail-concerns" id="concerns"><div className="section-heading"><div><p className="kicker">02 · We may assess</p><h2>Suitable<br/><i>concerns.</i></h2></div><p>Suitability and expected response vary. A listed concern does not mean the treatment is automatically appropriate.</p></div><div className="detail-card-grid">{item.concerns.map((c,i)=><article key={c}><span>0{i+1}</span><h3>{c}</h3><p>Assessment is required before a personalised recommendation is made.</p></article>)}</div></section>
  <section className="detail-appointment" id="appointment"><div><p className="kicker">03 · Your appointment</p><h2>Before, during<br/><i>& after.</i></h2></div><div className="detail-steps"><article><h3>Before</h3><p>{item.before}</p></article><article><h3>During</h3><p>{item.during}</p></article><article><h3>After</h3><p>{item.after}</p></article></div></section>
  <section className="detail-faq" id="questions"><div><p className="kicker">Question & answer</p><h2>Good to<br/><i>know.</i></h2></div><div className="faq-list"><details><summary><span>01</span><strong>How is suitability confirmed?</strong><i>＋</i></summary><p>We review the concern, medical history, current products or medications, relevant risks and realistic expectations.</p></details><details><summary><span>02</span><strong>Where can I see the price?</strong><i>＋</i></summary><p>Confirmed facial prices are shown on the Pricing page. Other procedures require consultation and a personalised quotation; we do not publish an unconfirmed price.</p></details><details><summary><span>03</span><strong>Are results guaranteed?</strong><i>＋</i></summary><p>No. Response, recovery and the number of sessions required vary between individuals.</p></details></div></section>
  <section className="split-cta"><h2>Start with<br/>a consultation.</h2><div><p>Receive a professional recommendation based on your skin, goals and suitability.</p><a className="button light-button" href="/book">Book now</a></div></section><Footer /></main>; }
