import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Footer, Header } from "../../site-chrome";
import "./treatment-detail.css";

const treatments = {
  "facial-treatments": { title:"Facial", italic:"treatments.", kicker:"Skin · Professional facials", intro:"Personalised professional facials selected for your skin condition, concerns and treatment goals.", principle:"Professional facial protocols combine skin assessment, cleansing, exfoliation and selected treatment products or devices. The exact facial is chosen after considering sensitivity, barrier condition and your current routine.", concerns:["Hydration and glow","Congestion and breakouts","Sensitivity and barrier support"], before:"Tell us about allergies, medications, active skin conditions, recent procedures and the products you currently use.", during:"Your practitioner selects the appropriate professional protocol, products and optional enhancements for your skin.", after:"You receive relevant home-care and sun-protection advice. Temporary redness or sensitivity can vary by treatment." },
  "laser-facial": { title:"CO₂ Laser", italic:"resurfacing.", kicker:"Skin · Ablative laser", intro:"A consultation-led CO₂ laser resurfacing pathway for appropriate texture, scarring and photo-ageing concerns.", principle:"CO₂ laser uses an ablative wavelength to create controlled treatment zones in the skin. Treatment depth, coverage and settings depend on the device, treatment area, skin assessment and clinical suitability.", concerns:["Texture and selected scarring","Photo-ageing appearance","Resurfacing consultation"], prices:[["Eye area",499,399],["Mouth or chin",499,399],["Forehead",499,399],["Cheeks",699,559],["Neck",699,559],["Décolletage",799,639],["Full face",1299,1039],["Full face + neck",1699,1359],["Face + neck + décolletage",2199,1759],["Scar or small area",299,239]], before:"A qualified practitioner must assess your medical history, skin type, medications, healing history, infection risk and recent procedures. Preparation requirements vary.", during:"Protective eyewear and an appropriate comfort plan are used. Treatment settings and time depend on the area and prescribed treatment depth.", after:"Redness, swelling, sensitivity, crusting and downtime may occur. Follow wound-care, infection-prevention and strict sun-protection instructions provided by your practitioner." },
  "dmk-enzyme-therapy": { title:"DMK Enzyme", italic:"therapy.", kicker:"Skin · Enzyme therapy", intro:"A structured professional skin revision treatment selected after assessing your skin, goals and current routine.", principle:"DMK Enzyme Therapy uses professional formulations and a characteristic setting mask within an individually planned skin revision pathway.", concerns:["Congestion and imbalance","Barrier and skin function","Texture and appearance"], before:"Your practitioner reviews current products, sensitivities and active skin conditions before selecting a level.", during:"Professional products are layered before the enzyme mask sets firmly on the skin.", after:"Home care and timing of future treatments are discussed according to your individual response." },
  "led-light-therapy": { title:"LED Light", italic:"therapy.", kicker:"Skin · Light therapy", intro:"A non-invasive light treatment that may be used alone or alongside selected professional facial treatments.", principle:"LED devices emit selected wavelengths of low-level light. The wavelength, duration and treatment plan are chosen for the intended professional protocol.", concerns:["Post-treatment support","Red or reactive appearance","Maintenance care"], before:"Skin is assessed and eye protection is provided. Photosensitising medication must be disclosed.", during:"You rest beneath the LED device while the selected light programme runs.", after:"There is generally minimal interruption to daily activities, although individual responses vary." },
  "hifu-ultherapy": { title:"Ultherapy®", italic:"skin lifting.", kicker:"Methods · Microfocused ultrasound with visualisation", intro:"Personalised, non-invasive skin lifting using genuine Ultherapy® ultrasound technology with real-time visualisation.", principle:"Ultherapy® combines real-time ultrasound imaging with microfocused ultrasound energy. Visualisation allows the practitioner to view tissue layers and plan precise energy delivery at selected depths without cutting or disrupting the skin surface.", concerns:["Brow lifting","Under chin and neck","Décolletage lines"], before:"A qualified practitioner reviews your anatomy, skin laxity, medical history, implanted devices, previous procedures and treatment goals before creating an individual Ultherapy® plan.", during:"Ultrasound gel is applied and real-time imaging is used to visualise the treatment area. You may feel brief heat or tingling as energy is delivered at the planned depths.", after:"There is generally minimal interruption to normal activities. Temporary redness, swelling, tenderness, bruising, pain or transient nerve effects may occur. Visible change develops gradually and individual results vary." },
  "rf-microneedling": { title:"RF", italic:"microneedling.", kicker:"Methods · Radiofrequency", intro:"A professional procedure combining controlled microneedling with radiofrequency energy for suitable skin concerns.", principle:"Insulated or non-insulated microneedles create controlled channels while radiofrequency energy is delivered at selected depths.", concerns:["Texture and pores","Selected acne-scar concerns","Firmness appearance"], before:"Suitability, infection risk, medications, healing history and treatment area are assessed first.", during:"Topical anaesthetic may be used. Settings and depth are selected for the treatment area and goal.", after:"Redness, swelling and sensitivity can occur. Follow infection-prevention and sun-protection advice carefully." },
  "skin-booster": { title:"Skin Booster", italic:"consultation.", kicker:"Aesthetics · Skin quality", intro:"A consultation pathway for clients interested in professional skin-quality and hydration options.", principle:"Skin booster is a broad marketing term and may refer to different products or procedures. The exact product, practitioner, risks, expected benefit and cost must be confirmed in consultation.", concerns:["Hydration goals","Skin-quality concerns","Personalised aesthetic planning"], before:"Medical history, allergies, medications, pregnancy status and treatment expectations require assessment.", during:"The precise procedure depends on the legally supplied product and the qualified treating practitioner.", after:"Recovery, risks and aftercare vary by procedure. You will receive product-specific information before consenting." },
} as const;

type Slug = keyof typeof treatments;

const sciencePaths: Record<Slug, readonly [string, string][]> = {
  "facial-treatments": [["Assess", "Barrier condition, sensitivity and current routine are reviewed."], ["Select", "Products, exfoliation and optional devices are chosen for the skin."], ["Support", "Home care and treatment timing support the planned outcome."]],
  "laser-facial": [["Fractional delivery", "Controlled CO₂ laser treatment zones are created at prescribed depth and coverage."], ["Remodelling response", "The controlled thermal and ablative response initiates a healing process."], ["Recovery", "New surface tissue forms while deeper remodelling continues over time."]],
  "dmk-enzyme-therapy": [["Prepare", "Professional products are selected according to skin condition and goals."], ["Enzyme mask", "The characteristic setting mask is applied as part of the prescribed protocol."], ["Skin revision", "Treatment and home care are planned as a progressive skin-management pathway."]],
  "led-light-therapy": [["Selected wavelength", "A professional LED programme emits a selected wavelength of low-level light."], ["Light interaction", "Light reaches the skin without ablating or resurfacing the surface."], ["Protocol support", "Session duration and frequency are selected for the intended treatment pathway."]],
  "hifu-ultherapy": [["See", "Real-time ultrasound visualisation allows the practitioner to view tissue layers before energy delivery."], ["Treat", "Microfocused ultrasound creates precise treatment points at selected 1.5 mm, 3.0 mm and 4.5 mm depths, where appropriate."], ["Lift gradually", "The body's collagen-building response develops over time, with visible change commonly assessed over the following months."]],
  "rf-microneedling": [["Controlled depth", "Microneedles are placed at practitioner-selected depths within the treatment area."], ["RF delivery", "Radiofrequency energy is delivered through the needle array in controlled zones."], ["Repair response", "Redness settles while the skin's remodelling response develops over time."]],
  "skin-booster": [["Medical assessment", "The practitioner confirms the exact product, indication and legal treatment pathway."], ["Personalised plan", "Placement, amount and technique depend on anatomy and the prescribed product."], ["Review", "Recovery and results are reviewed according to product-specific guidance."]],
};

const safetyNotes: Record<Slug, string> = {
  "facial-treatments": "Active infection, significant irritation, allergies, recent procedures and barrier impairment may change the recommended facial.",
  "laser-facial": "Skin type, medications, infection risk, scarring history and healing capacity must be assessed. Ablative CO₂ laser involves downtime and requires strict aftercare.",
  "dmk-enzyme-therapy": "Sensitivity, allergies, active inflammation and current products must be disclosed before a professional protocol is selected.",
  "led-light-therapy": "Photosensitising medication, eye conditions and relevant medical history must be disclosed. Protective eyewear is required.",
  "hifu-ultherapy": "Ultherapy® must be delivered by an appropriately trained practitioner. Anatomy, implanted devices, medical history and previous procedures require assessment. The system must not be used on the eyes or where ultrasound energy could reach the eye.",
  "rf-microneedling": "Active infection, pregnancy status, medications, implanted devices, healing history and pigment-change risk require assessment.",
  "skin-booster": "Only a qualified practitioner can confirm the exact product, risks and suitability. Product-specific consent is required before treatment.",
};
export function generateStaticParams(){ return Object.keys(treatments).map(slug=>({slug})); }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{ const {slug}=await params; const item=treatments[slug as Slug]; return item?{title:`${item.title} | VenuX Skin Clinic`,description:item.intro}:{}; }

export default async function TreatmentDetail({params}:{params:Promise<{slug:string}>}){ const {slug}=await params; const item=treatments[slug as Slug]; if(!item) notFound(); const science=sciencePaths[slug as Slug]; const safety=safetyNotes[slug as Slug]; return <main><Header />
  <section className="detail-hero"><div><a className="back-link" href="/treatments">← All treatments</a><p className="kicker">{item.kicker}</p><h1>{item.title}<br/><i>{item.italic}</i></h1><p>{item.intro}</p><div className="hero-actions"><a className="button dark" href="/book">Book a consultation</a><a className="text-link" href="#details">Learn more ↓</a></div></div>{slug==="hifu-ultherapy"?<div className="ultherapy-hero-media"><img src="https://ultherapy.com.au/wp-content/uploads/goes-deeper.jpg" alt="Official Ultherapy system and treatment handpiece" /><div className="ultherapy-hero-shade"/><div className="ultherapy-brand-wordmark" aria-label="Ultherapy"><b>u</b><span>Ultherapy®</span></div><small>Official Ultherapy® technology</small></div>:<div className="detail-orbit" aria-hidden="true"><i/><i/><span>V</span></div>}</section>
  <nav className="detail-nav"><a href="#principle">01 · Principle</a><a href="#concerns">02 · Concerns</a>{"prices" in item&&<a href="#pricing">03 · Pricing</a>}<a href="#appointment">{"prices" in item?"04":"03"} · Appointment</a><a href="#questions">{"prices" in item?"05":"04"} · Questions</a></nav>
  <section className="detail-principle clinical-principle" id="principle"><div className="principle-intro"><p className="kicker">01 · How it works</p><h2>Professional<br/><i>principle.</i></h2><p>{item.principle}</p></div><div className="principle-pathway">{slug==="hifu-ultherapy"?<figure className="ultherapy-imaging"><img src="https://ultherapy.com.au/wp-content/uploads/banner-image.jpg" alt="Ultherapy real-time ultrasound imaging and personalised treatment mapping screen" /><figcaption><strong>SEE + TREAT</strong><span>Real-time visualisation supports personalised energy delivery.</span></figcaption></figure>:<div className={`treatment-visual visual-${slug}`} aria-hidden="true"><span>{item.title}</span><i/><i/><i/></div>}<div className="principle-steps">{science.map(([title,copy],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><aside><strong>Why assessment matters</strong><p>{safety}</p></aside></div></section>
  <section className="detail-concerns" id="concerns"><div className="section-heading"><div><p className="kicker">02 · We may assess</p><h2>Suitable<br/><i>concerns.</i></h2></div><p>Suitability and expected response vary. A listed concern does not mean the treatment is automatically appropriate.</p></div>{slug==="hifu-ultherapy"&&<figure className="ultherapy-concern-visual"><img src="https://ultherapy.com/app/themes/ultherapy2020/static/images/pages/consumer/discover-signature-lift-triple-images-v2.webp" alt="Official Ultherapy campaign image showing a diverse range of adults" /><figcaption>Official Ultherapy® campaign image · Models shown are not actual patients.</figcaption></figure>}<div className="detail-card-grid">{item.concerns.map((c,i)=><article key={c}><span>0{i+1}</span><h3>{c}</h3><p>Assessment is required before a personalised recommendation is made.</p></article>)}</div></section>
  {"prices" in item&&<section className="co2-pricing" id="pricing"><div className="section-heading"><div><p className="kicker">03 · Indicative pricing</p><h2>Pricing by<br/><i>treatment area.</i></h2></div><p>Prices are starting guides in AUD. Final price depends on assessment, treatment depth, coverage, practitioner and aftercare requirements.</p></div><div className="co2-price-key"><span>Area</span><span>Regular from</span><span>Member from</span></div><div className="co2-price-list">{item.prices.map(([area,regular,member])=><div key={area}><strong>{area}</strong><b>${regular}</b><em>${member}</em></div>)}</div><p className="co2-price-note">CO₂ laser is consultation-led. Suitability, downtime, risks and your final quotation are confirmed before booking treatment.</p></section>}
  <section className="detail-appointment" id="appointment"><div><p className="kicker">03 · Your appointment</p><h2>Before, during<br/><i>& after.</i></h2></div><div className="detail-steps"><article><h3>Before</h3><p>{item.before}</p></article><article><h3>During</h3><p>{item.during}</p></article><article><h3>After</h3><p>{item.after}</p></article></div></section>
  <section className="detail-faq" id="questions"><div><p className="kicker">Question & answer</p><h2>Good to<br/><i>know.</i></h2></div><div className="faq-list"><details><summary><span>01</span><strong>How is suitability confirmed?</strong><i>＋</i></summary><p>We review the concern, medical history, current products or medications, relevant risks and realistic expectations.</p></details><details><summary><span>02</span><strong>Where can I see the price?</strong><i>＋</i></summary><p>{"prices" in item ? "Indicative starting prices are shown on this page. Your final quotation is confirmed after clinical assessment." : "Confirmed facial prices are shown on the Pricing page. Other procedures require consultation and a personalised quotation; we do not publish an unconfirmed price."}</p></details><details><summary><span>03</span><strong>Are results guaranteed?</strong><i>＋</i></summary><p>No. Response, recovery and the number of sessions required vary between individuals.</p></details></div></section>
  <section className="split-cta"><h2>Start with<br/>a consultation.</h2><div><p>Receive a professional recommendation based on your skin, goals and suitability.</p><a className="button light-button" href="/book">Book now</a></div></section><Footer /></main>; }
