import type {Metadata} from "next";
import {getAdminRole,isAdminAuthenticated} from "../../../lib/admin-auth";
import {getAppointments,getAppointmentsRange,getDormantClients,getStaff} from "../../../lib/clinic-admin";
import {queueReturnInviteAction} from "../actions";
import {AdminLogin,AdminShell,statusLabel} from "../admin-ui";
import "../admin.css";
import "../bookings/bookings.css";
import "../bookings/bookings-updates.css";

export const dynamic="force-dynamic";
export const metadata:Metadata={title:"Calendar | ISA Skin Clinic & Aesthetics",robots:{index:false,follow:false}};
const todaySydney=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Australia/Sydney",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const monthBounds=(date:string)=>{const [year,month]=date.split("-").map(Number),first=new Date(Date.UTC(year,month-1,1)),last=new Date(Date.UTC(year,month,0)),previous=new Date(Date.UTC(year,month-2,1)),next=new Date(Date.UTC(year,month,1));return {from:first.toISOString().slice(0,10),to:last.toISOString().slice(0,10),days:last.getUTCDate(),leading:(first.getUTCDay()+6)%7,label:first.toLocaleDateString("en-AU",{month:"long",year:"numeric",timeZone:"UTC"}),previous:previous.toISOString().slice(0,10),next:next.toISOString().slice(0,10)};};
const timeMinutes=(value:string)=>{const match=value.match(/^(\d{1,2}):(\d{2})\s*(AM|PM)$/i);if(!match)return 9999;let hour=Number(match[1])%12;if(match[3].toUpperCase()==="PM")hour+=12;return hour*60+Number(match[2]);};

export default async function CalendarPage({searchParams}:{searchParams:Promise<{date?:string;error?:string;queued?:string}>}){
  const params=await searchParams;if(!(await isAdminAuthenticated()))return <AdminLogin error={params.error}/>;
  const role=await getAdminRole(),location=role==="staff"?"Top Ryde":"",date=/^\d{4}-\d{2}-\d{2}$/.test(params.date??"")?String(params.date):todaySydney(),month=monthBounds(date);
  const [rows,monthlyRows,staff,dormantClients]=await Promise.all([getAppointments(date,location),getAppointmentsRange(month.from,month.to,location),getStaff(),getDormantClients(120)]);
  const successful=new Set(["confirmed","in_progress","completed"]),activeStaff=staff.filter(person=>person.active),visibleRows=rows.filter(row=>successful.has(String(row.status))),dayCount=visibleRows.length;
  const calendarDays=Array.from({length:month.days},(_,index)=>{const iso=`${month.from.slice(0,8)}${String(index+1).padStart(2,"0")}`,appointments=monthlyRows.filter(row=>String(row.requested_date).slice(0,10)===iso&&successful.has(String(row.status)));return {iso,day:index+1,appointments};});
  const reminderClients=dormantClients.filter(client=>role==="owner"||String(client.clinic_location)==="Top Ryde").slice(0,6);
  return <AdminShell active="Calendar"><header className="clinic-admin-head"><div><p>Monthly overview & daily schedule</p><h1>Appointment calendar</h1></div><a className="calendar-new-booking" href={`/admin/bookings?date=${date}#booking`}>+ New appointment</a></header>
    {params.queued==="1"?<div className="clinic-alert">Return invitation added to Messages.</div>:params.queued==="0"?<div className="clinic-alert error">Invitation already exists this month or marketing consent is unavailable.</div>:null}
    <form method="get" className="day-picker calendar-date-picker"><label>Selected date<input name="date" type="date" defaultValue={date}/></label><button>Show day</button></form>
    <section className="month-overview"><header><a href={`/admin/calendar?date=${month.previous}`} aria-label="Previous month">←</a><div><small>Monthly calendar</small><h2>{month.label}</h2></div><a href={`/admin/calendar?date=${month.next}`} aria-label="Next month">→</a></header><div className="calendar-count-key"><span className="count-empty">0</span><span className="count-low">1–2</span><span className="count-ready">3+</span></div><div className="month-weekdays">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(day=><span key={day}>{day}</span>)}</div><div className="month-grid">{Array.from({length:month.leading},(_,index)=><span className="month-empty" key={`empty-${index}`}/>)}{calendarDays.map(day=>{const count=day.appointments.length,countClass=count===0?"count-empty":count<3?"count-low":"count-ready";return <a className={`${day.iso===date?"selected ":""}${countClass}`} href={`/admin/calendar?date=${day.iso}#day-appointments`} key={day.iso}><strong>{day.day}</strong><span>{count} booked</span>{count?<small>{day.appointments.slice(0,2).map(appointment=>appointment.staff_name?String(appointment.staff_name):"Unassigned").join(" · ")}</small>:<small>Available</small>}</a>;})}</div></section>
    {dayCount<3?<section className="low-booking-reminder"><header><div><small>Automatic low-booking reminder</small><h2>Only {dayCount} confirmed appointment{dayCount===1?"":"s"} on this day</h2></div><a href="/admin/retention">Open full retention list →</a></header><p>Consider contacting clients who have not completed a visit for at least 120 days. Marketing SMS is only available where consent is recorded.</p><div>{reminderClients.map(client=><article key={String(client.id)}><strong>{String(client.full_name)}</strong><small>{client.last_visit?`Last visit ${new Date(String(client.last_visit)).toLocaleDateString("en-AU")}`:"No completed visit"}</small><span><a href={`/admin/clients/${client.id}`}>Profile</a><a href={`/admin/bookings?date=${date}&client=${client.id}#booking`}>Book</a></span>{client.marketing_sms_consent&&!client.sms_unsubscribed_at?<form action={queueReturnInviteAction}><input type="hidden" name="clientId" value={String(client.id)}/><input type="hidden" name="returnTo" value={`/admin/calendar?date=${date}`}/><button>Invite</button></form>:<em>Call only</em>}</article>)}</div></section>:null}
    <section className="calendar-day-list" id="day-appointments"><header><div><small>Selected day</small><h2>{new Date(`${date}T00:00:00Z`).toLocaleDateString("en-AU",{weekday:"long",day:"numeric",month:"long",timeZone:"UTC"})}</h2></div><span>{dayCount} active bookings</span></header>{visibleRows.length?<div className="calendar-appointment-grid">{visibleRows.toSorted((a,b)=>timeMinutes(String(a.requested_time))-timeMinutes(String(b.requested_time))).map((row,index)=><a className={`calendar-appointment colour-${index%5}`} href={`/admin/bookings?date=${date}#appointment-${row.id}`} key={String(row.id)}><time>{String(row.requested_time)}</time><strong>{String(row.full_name)}</strong><span>{String(row.treatment)}</span><small>{row.staff_name?String(row.staff_name):"Unassigned"} · {statusLabel(row.status)}</small></a>)}</div>:<div className="empty-admin">No active appointments on this day.</div>}<div className="calendar-staff-actions">{activeStaff.map((person,index)=><a className={`colour-${index%5}`} href={`/admin/bookings?date=${date}&staff=${person.id}#booking`} key={String(person.id)}>Book with {String(person.full_name)} →</a>)}</div></section>
  </AdminShell>;
}
