"use client";

import {useEffect,useRef,useState} from "react";

type ClientSuggestion={id:number;name:string;mobile:string;email:string;clinicLocation:string;membershipStatus:string;visitCount:number};
type SearchField="name"|"mobile";
type SearchStatus="idle"|"searching"|"ready"|"error";

export function AppointmentClientPicker({initialClient}:{initialClient?:ClientSuggestion}){
  const [name,setName]=useState(initialClient?.name??""),[mobile,setMobile]=useState(initialClient?.mobile??""),[email,setEmail]=useState(initialClient?.email??""),[clinicLocation,setClinicLocation]=useState(initialClient?.clinicLocation??""),[clientId,setClientId]=useState(initialClient?.id??0),[results,setResults]=useState<ClientSuggestion[]>([]),[open,setOpen]=useState(false),[searchField,setSearchField]=useState<SearchField>("name"),[status,setStatus]=useState<SearchStatus>("idle"),[retryKey,setRetryKey]=useState(0),skipNext=useRef(false);
  useEffect(()=>{if(skipNext.current){skipNext.current=false;return;}const cleanName=name.trim(),phoneDigits=mobile.replace(/\D/g,"");const query=searchField==="mobile"?(phoneDigits.length>=3?phoneDigits:""):(cleanName.length>=2?cleanName:"");if(!query){setResults([]);setOpen(false);setStatus("idle");return;}const controller=new AbortController();setOpen(true);setStatus("searching");const timer=window.setTimeout(async()=>{try{const response=await fetch(`/admin/api/clients/search?q=${encodeURIComponent(query)}`,{signal:controller.signal,cache:"no-store",credentials:"same-origin"});if(!response.ok)throw new Error(`Search failed (${response.status})`);const data=await response.json() as {clients?:ClientSuggestion[]};setResults(Array.isArray(data.clients)?data.clients:[]);setStatus("ready");}catch(error){if((error as Error).name!=="AbortError"){setResults([]);setStatus("error");}}},250);return()=>{window.clearTimeout(timer);controller.abort();};},[name,mobile,searchField,retryKey]);
  const choose=(client:ClientSuggestion)=>{skipNext.current=true;setClientId(client.id);setName(client.name);setMobile(client.mobile);setEmail(client.email);setClinicLocation(client.clinicLocation);setResults([]);setOpen(false);setStatus("idle");};
  const clearSelection=()=>{if(!clientId)return;setClientId(0);setMobile("");setEmail("");setClinicLocation("");};
  const resultList=open?<div className="client-options" id={`appointment-client-${searchField}-options`} role="listbox" aria-live="polite">{status==="searching"?<p>Searching clients…</p>:status==="error"?<p>Search could not load. <button className="client-search-retry" type="button" onClick={()=>setRetryKey(value=>value+1)}>Try again</button></p>:results.length?results.map(client=><button type="button" role="option" key={client.id} onMouseDown={event=>event.preventDefault()} onClick={()=>choose(client)}><strong>{client.name}<em className={`clinic-location-badge ${client.clinicLocation==="City"?"city":"ryde"}`}>{client.clinicLocation}</em></strong><span>{client.mobile}{client.email?` · ${client.email}`:""}</span><small>{client.visitCount} appointments · {client.membershipStatus||"Standard client"}</small></button>):<p>No matching client — complete the fields to create a new profile.</p>}</div>:null;
  return <div className="appointment-client-picker">
    <input type="hidden" name="clientId" value={clientId||""}/>
    <label>Client name<div className="client-combobox"><input name="name" required value={name} onFocus={()=>{setSearchField("name");if(name.trim().length>=2)setOpen(true);}} onChange={event=>{setSearchField("name");clearSelection();setName(event.target.value);}} autoComplete="one-time-code" autoCorrect="off" spellCheck={false} role="combobox" aria-expanded={open&&searchField==="name"} aria-controls="appointment-client-name-options" placeholder="Type client name to search"/>{clinicLocation?<em className={`selected-location clinic-location-badge ${clinicLocation==="City"?"city":"ryde"}`}>{clinicLocation}</em>:null}{searchField==="name"?resultList:null}</div></label>
    <label className="client-mobile-field">Mobile<div className="client-combobox"><input name="mobile" required inputMode="tel" value={mobile} onFocus={()=>{setSearchField("mobile");if(mobile.replace(/\D/g,"").length>=3)setOpen(true);}} onChange={event=>{setSearchField("mobile");if(clientId){setClientId(0);setName("");setEmail("");setClinicLocation("");}setMobile(event.target.value);}} autoComplete="one-time-code" role="combobox" aria-expanded={open&&searchField==="mobile"} aria-controls="appointment-client-mobile-options" placeholder="Type at least 3 digits to search"/>{searchField==="mobile"?resultList:null}</div></label>
    <label>Email<input name="email" type="email" value={email} onChange={event=>setEmail(event.target.value)} autoComplete="one-time-code"/></label>
  </div>;
}
