import type { Metadata } from "next";
import { isAdminAuthenticated } from "../../../lib/admin-auth";
import { getAppointments } from "../../../lib/clinic-admin";
import { changeAppointment } from "../actions";
import { AdminLogin,AdminShell,statusLabel } from "../admin-ui";
import "../admin.css";
export const dynamic="force-dynamic"; export const metadata:Metadata={title:"Bookings | VenuX Clinic OS",robots:{index:false,follow:false}};
export default async function BookingsAdmin({searchParams}:{searchParams:Promise<{saved?:string;error?:string}>}){const params=await searchParams;if(!(await isAdminAuthenticated()))return <AdminLogin error={params.error}/>;const rows=await getAppointments();return <AdminShell active="Bookings"><header className="clinic-admin-head"><div><p>Calendar & requests</p><h1>Bookings</h1></div><span>{rows.length} records</span></header>{params.saved&&<div className="clinic-alert">Appointment updated.</div>}{params.error&&<div className="clinic-alert error">Please check the appointment values.</div>}<div className="admin-table"><div className="admin-table-head"><span>Date & time</span><span>Client</span><span>Treatment & clinic</span><span>Status</span><span>Update</span></div>{rows.length?rows.map(row=><div className="booking-admin-row" key={String(row.id)}><div><strong>{new Date(String(row.requested_date)).toLocaleDateString("en-AU")}</strong><small>{String(row.requested_time)}</small></div><div><strong>{String(row.full_name)}</strong><small>{String(row.mobile)} · {String(row.email)}</small></div><div><strong>{String(row.treatment)}</strong><small>{String(row.clinic)}</small></div><div><span className={`status-pill ${row.status}`}>{statusLabel(row.status)}</span><small>Deposit: {statusLabel(row.deposit_status)}</small></div><form action={changeAppointment}><input type="hidden" name="id" value={String(row.id)}/><select name="status" defaultValue={String(row.status)} aria-label={`Status for ${row.full_name}`}><option value="requested">Requested</option><option value="confirmed">Confirmed</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option><option value="no_show">No-show</option></select><select name="depositStatus" defaultValue={String(row.deposit_status)} aria-label={`Deposit for ${row.full_name}`}><option value="unpaid">Deposit unpaid</option><option value="paid">Deposit paid</option><option value="refunded">Refunded</option><option value="forfeited">Forfeited</option></select><input name="totalAmount" type="number" min="0" step="1" defaultValue={Number(row.total_amount)} aria-label={`Revenue for ${row.full_name}`}/><button type="submit">Save appointment</button></form></div>):<div className="empty-admin">No appointments yet. Website booking requests will appear here.</div>}</div></AdminShell>}

