import type { Metadata } from "next";
import { isAdminAuthenticated } from "../../../lib/admin-auth";
import { getAppointments,getAppointmentsRange,getClientForBooking,getOwnerServices,getStaff } from "../../../lib/clinic-admin";
import { changeAppointment,createAdminAppointment,finishAppointmentAction,startAppointmentAction } from "../actions";
import { AdminLogin,AdminShell,statusLabel } from "../admin-ui";
import {AppointmentClientPicker} from "./appointment-client-picker";
import "../admin.css";
import "./bookings.css";
import "./bookings-updates.css";

export const dynamic="force-dynamic";
export const metadata:Metadata={title:"Bookings | VenuX Clinic OS",robots:{index:false,follow:false}};
const times=["10:00 AM","11:00 AM","12:00 PM","1:30 PM","2:30 PM","3:30 PM","4:30 PM","5:30 PM"];
const todaySydney=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Australia/Sydney",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const weekBounds=(date:string)=>{const selected=new Date(`${date}T00:00:00Z`),day=selected.getUTCDay()||7,monday=new Date(selected);monday.setUTCDate(selected.getUTCDate()-day+1);const sunday=new Date(monday);sunday.setUTCDate(monday.getUTCDate()+6);return {from:monday.toISOString().slice(0,10),to:sunday.toISOString().slice(0,10)};};

export default async function BookingsAdmin({searchParams}:{searchParams:Promise<{saved?:string;created?:string;started?:string;finished?:string;error?:string;client?:string;date?:string}>}){
  const params=await searchParams;if(!(await isAdminAuthenticated()))return <AdminLogin error={params.error}/>;
  const date=/^\d{4}-\d{2}-\d{2}$/.test(params.date??"")?String(params.date):todaySydney();
  const clientId=Number(params.client??0),week=weekBounds(date);
  const [rows,weeklyRows,staff,services,selectedClient]=await Promise.all([
    getAppointments(date),getAppointmentsRange(week.from,week.to),getStaff(),getOwnerServices(),clientId>0?getClientForBooking(clientId):null,
  ]);
  const activeServices=services.filter(row=>row.active),servicesByCategory=new Map<string,typeof activeServices>();
  for(const service of activeServices){const category=String(service.category);servicesByCategory.set(category,[...(servicesByCategory.get(category)??[]),service]);}
  const days=Array.from({length:7},(_,index)=>{const value=new Date(`${week.from}T00:00:00Z`);value.setUTCDate(value.getUTCDate()+index);const iso=value.toISOString().slice(0,10);return {iso,rows:weeklyRows.filter(row=>String(row.requested_date).slice(0,10)===iso)};});
  const treatmentCounts=new Map<string,number>();for(const row of weeklyRows){if(!["cancelled","no_show"].includes(String(row.status)))treatmentCounts.set(String(row.treatment),(treatmentCounts.get(String(row.treatment))??0)+1);}const treatmentFrequency=[...treatmentCounts].sort((a,b)=>b[1]-a[1]);
  return <AdminShell active="Bookings"><header className="clinic-admin-head"><div><p>Calendar & client booking</p><h1>Weekly bookings</h1></div><span>{weeklyRows.length} appointments · {week.from} to {week.to}</span></header>
    {params.saved?<div className="clinic-alert">Appointment updated. Confirmed appointments with SMS consent create a customer confirmation message.</div>:null}
    {params.created?<div className="clinic-alert">Appointment created and connected to the client record.</div>:null}
    {params.started?<div className="clinic-alert">Service started. The project wage will be added when the service ends.</div>:null}
    {params.finished?<div className="clinic-alert">Service completed. The fixed project wage has been added to payroll.</div>:null}
    {params.error?<div className="clinic-alert error">{params.error==="conflict"?"That clinic, date and time is already reserved. No duplicate appointment was created.":params.error==="staff"?"Assign a beautician before starting the service.":"Please check the appointment values."}</div>:null}

    <section className="booking-tools single">
      <form method="get" className="day-picker"><label>View appointment date<input name="date" type="date" defaultValue={date}/></label><button>Show day</button></form>
    </section>

    <section className="week-overview"><header><div><small>Selected week</small><h2>Monday to Sunday</h2></div><span>{weeklyRows.length} total appointments</span></header><div className="week-grid">{days.map(day=><article className={day.iso===date?"selected":""} key={day.iso}><a href={`/admin/bookings?date=${day.iso}`}><small>{new Date(`${day.iso}T00:00:00Z`).toLocaleDateString("en-AU",{weekday:"short"})}</small><strong>{new Date(`${day.iso}T00:00:00Z`).getUTCDate()}</strong><span>{day.rows.length} booked</span></a><div>{day.rows.length?day.rows.map(row=><a className="week-booking" href={`/admin/bookings?date=${day.iso}`} key={String(row.id)}><time>{String(row.requested_time)}</time><strong>{String(row.full_name)} <em className={`clinic-location-badge ${String(row.clinic_location)==="City"?"city":"ryde"}`}>{String(row.clinic_location??"Top Ryde")}</em></strong><span>{String(row.treatment)}</span><small>{row.staff_name?String(row.staff_name):"Unassigned"}</small></a>):<p>No bookings</p>}</div></article>)}</div></section>

    <section className="frequency-panel"><header><div><small>Weekly demand</small><h2>Treatment frequency</h2></div><span>Cancelled and no-show excluded</span></header><div>{treatmentFrequency.length?treatmentFrequency.map(([treatment,count],index)=><article key={treatment}><b>{String(index+1).padStart(2,"0")}</b><span><strong>{treatment}</strong><small>{count} appointment{count===1?"":"s"} this week</small></span><em>{count}</em></article>):<p>No treatment frequency yet for this week.</p>}</div></section>

    <details className="admin-booking-create" open><summary>+ Book an appointment {selectedClient?`for ${selectedClient.full_name}`:"for a client"}</summary><form action={createAdminAppointment}>
      <AppointmentClientPicker initialClient={selectedClient?{id:Number(selectedClient.id),name:String(selectedClient.full_name),mobile:String(selectedClient.mobile),email:String(selectedClient.email??""),clinicLocation:String(selectedClient.clinic_location??"Top Ryde"),membershipStatus:String(selectedClient.membership_status??"non-member"),visitCount:Number(selectedClient.visit_count??0)}:undefined}/><label>Treatment<select name="serviceId" required defaultValue=""><option value="" disabled>Select treatment</option>{[...servicesByCategory].map(([category,categoryServices])=><optgroup label={category} key={category}>{categoryServices.map(service=><option value={String(service.id)} key={String(service.id)}>{String(service.service_name)}</option>)}</optgroup>)}</select></label><label>Beautician<select name="staffId" defaultValue=""><option value="">Assign later</option>{staff.filter(person=>person.active).map(person=><option value={String(person.id)} key={String(person.id)}>{String(person.full_name)}</option>)}</select></label><label>Clinic<select name="clinic" required defaultValue=""><option value="" disabled>Select clinic</option><option>Top Ryde · Shop 3002</option><option>Sydney City · 515 Kent Street</option></select></label><label>Date<input name="date" type="date" required defaultValue={date}/></label><label>Time<select name="time" required defaultValue=""><option value="" disabled>Select time</option>{times.map(time=><option key={time}>{time}</option>)}</select></label><label className="booking-notes">Notes<textarea name="notes"/></label><label className="booking-check"><input type="checkbox" name="serviceSmsConsent" value="yes" defaultChecked={Boolean(selectedClient?.service_sms_consent)}/> Client agreed to appointment SMS</label><label className="booking-check"><input type="checkbox" name="marketingSmsConsent" value="yes" defaultChecked={Boolean(selectedClient?.marketing_sms_consent)}/> Client expressly agreed to birthday/marketing SMS</label><button>Create appointment</button></form></details>

    <div className="daily-heading"><div><small>Today / selected date</small><h2>All appointments</h2></div><span>{rows.length} total</span></div>
    <div className="admin-table"><div className="admin-table-head"><span>Time</span><span>Client</span><span>Treatment & clinic</span><span>Status</span><span>Update</span></div>{rows.length?rows.map(row=><div className="booking-admin-row" key={String(row.id)}>
      <div><strong>{String(row.requested_time)}</strong><small>{new Date(String(row.requested_date)).toLocaleDateString("en-AU")} · {String(row.source??"website")}</small></div>
      <div><strong>{String(row.full_name)} <span className={`clinic-location-badge ${String(row.clinic_location)==="City"?"city":"ryde"}`}>{String(row.clinic_location??"Top Ryde")}</span></strong><small>{String(row.mobile)} · {String(row.email)}</small><a href={`/admin/clients/${row.client_id}`}>Client record →</a></div>
      <div><strong>{String(row.treatment)}</strong><small>{String(row.clinic)} · {row.staff_name?String(row.staff_name):"Unassigned"}</small>{row.started_at?<small>Started {new Date(String(row.started_at)).toLocaleTimeString("en-AU",{hour:"2-digit",minute:"2-digit"})}{String(row.status)==="completed"?` · Project wage $${Number(row.staff_wage_amount??0).toLocaleString("en-AU")}`:" · Wage pending until end"}</small>:null}</div>
      <div><span className={`status-pill ${row.status}`}>{statusLabel(row.status)}</span><small>Client: {statusLabel(row.customer_confirmation_status??"pending")} · Deposit: {statusLabel(row.deposit_status)}</small>
        {!["in_progress","completed","cancelled","no_show"].includes(String(row.status))&&row.staff_id?<form action={startAppointmentAction} className="start-service-form"><input type="hidden" name="id" value={String(row.id)}/><input type="hidden" name="staffId" value={String(row.staff_id)}/><button type="submit">Start service</button></form>:null}
        {String(row.status)==="in_progress"&&row.staff_id?<form action={finishAppointmentAction} className="finish-service-form"><input type="hidden" name="id" value={String(row.id)}/><input type="hidden" name="staffId" value={String(row.staff_id)}/><textarea name="comment" required placeholder="Completion comment" aria-label={`Completion comment for ${row.full_name}`}/><label>Fee $<input name="manualFee" type="number" min="0" step="0.01" required defaultValue={Number(row.wage_project_rate||25)} aria-label={`Manual fee for ${row.full_name}`}/></label><button type="submit">End service & add wage</button></form>:null}
      </div>
      <form action={changeAppointment}><input type="hidden" name="id" value={String(row.id)}/><select name="staffId" defaultValue={row.staff_id?String(row.staff_id):""} aria-label={`Staff for ${row.full_name}`}><option value="">Unassigned staff</option>{staff.filter(person=>person.active).map(person=><option value={String(person.id)} key={String(person.id)}>{String(person.full_name)}</option>)}</select><select name="status" defaultValue={String(row.status)} aria-label={`Status for ${row.full_name}`}><option value="requested">Requested</option><option value="confirmed">Confirmed</option><option value="in_progress">In progress</option>{String(row.status)==="completed"?<option value="completed">Completed</option>:null}<option value="cancelled">Cancelled</option><option value="no_show">No-show</option></select><select name="depositStatus" defaultValue={String(row.deposit_status)} aria-label={`Deposit for ${row.full_name}`}><option value="unpaid">Deposit unpaid</option><option value="paid">Deposit paid</option><option value="refunded">Refunded</option><option value="forfeited">Forfeited</option></select><input name="totalAmount" type="hidden" value={Number(row.total_amount)}/><button type="submit">Save appointment</button></form>
    </div>):<div className="empty-admin">No appointments on this date. Website bookings will appear here automatically.</div>}</div>
  </AdminShell>;
}
