import type { Metadata } from "next";
import { randomUUID } from "node:crypto";
import { getAdminRole,isAdminAuthenticated } from "../../../lib/admin-auth";
import { getAppointments,getClientForBooking,getOwnerServices,getStaff } from "../../../lib/clinic-admin";
import { changeAppointment,createAdminAppointment,deleteCancelledAppointmentAction,finishAppointmentAction,startAppointmentAction } from "../actions";
import { AdminLogin,AdminShell,statusLabel } from "../admin-ui";
import {AppointmentClientPicker} from "./appointment-client-picker";
import {TreatmentPicker} from "./treatment-picker";
import "../admin.css";
import "./bookings.css";
import "./bookings-updates.css";
import "./service-photos.css";

export const dynamic="force-dynamic";
export const metadata:Metadata={title:"Appointments | ISA Skin Clinic & Aesthetics",robots:{index:false,follow:false}};
const formatTime=(minutes:number)=>{const hour24=Math.floor(minutes/60),minute=minutes%60,hour=hour24%12||12;return `${hour}:${String(minute).padStart(2,"0")} ${hour24<12?"AM":"PM"}`;};
const times=Array.from({length:67},(_,index)=>formatTime(10*60+index*10));
const todaySydney=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Australia/Sydney",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const timeMinutes=(value:string)=>{const match=value.match(/^(\d{1,2}):(\d{2})\s*(AM|PM)$/i);if(!match)return 9999;let hour=Number(match[1])%12;if(match[3].toUpperCase()==="PM")hour+=12;return hour*60+Number(match[2]);};

export default async function BookingsAdmin({searchParams}:{searchParams:Promise<{saved?:string;created?:string;started?:string;finished?:string;deleted?:string;error?:string;client?:string;date?:string;staff?:string;time?:string;overlap?:string}>}){
  const params=await searchParams;if(!(await isAdminAuthenticated()))return <AdminLogin error={params.error}/>;
  const role=await getAdminRole(),appointmentLocation=role==="staff"?"Top Ryde":"";
  const date=/^\d{4}-\d{2}-\d{2}$/.test(params.date??"")?String(params.date):todaySydney();
  const clientId=Number(params.client??0),selectedStaffId=Number(params.staff??0),selectedTime=times.includes(params.time??"")?String(params.time):"",submissionKey=randomUUID();
  const [rows,staff,services,selectedClientRow]=await Promise.all([
    getAppointments(date,appointmentLocation),getStaff(),getOwnerServices(),clientId>0?getClientForBooking(clientId):null,
  ]);
  const selectedClient=role==="staff"&&String(selectedClientRow?.clinic_location)==="City"?null:selectedClientRow;
  const activeServices=services.filter(row=>row.active).map(service=>({id:Number(service.id),name:String(service.service_name),category:String(service.category),regularPrice:Number(service.regular_price)}));
  const activeStaff=staff.filter(person=>person.active),gridTimes=[...new Set([...times,...rows.map(row=>String(row.requested_time))])].sort((a,b)=>timeMinutes(a)-timeMinutes(b));
  return <AdminShell active="Appointments"><header className="clinic-admin-head"><div><p>Create & manage bookings</p><h1>Appointments</h1></div><a className="calendar-new-booking" href={`/admin/calendar?date=${date}`}>Open calendar →</a></header>
    {params.saved?<div className="clinic-alert">Appointment updated. Confirmed appointments with SMS consent create a customer confirmation message.</div>:null}
    {params.created?<div className="clinic-alert">Appointment created and connected to the client record.</div>:null}
    {params.started?<div className="clinic-alert">Service started. Any supplied Before photo was saved to this appointment.</div>:null}
    {params.finished?<div className="clinic-alert">Service completed. The comment and any supplied After photo were saved to the client history, and a one-week follow-up reminder was created.</div>:null}
    {params.deleted?<div className="clinic-alert">Cancelled appointment permanently deleted by the owner.</div>:null}
    {params.error?<div className="clinic-alert error">{params.error==="conflict"?"This beautician already has an overlapping booking. Tick ‘Allow another booking’ if you want to book both clients at the same time.":params.error==="staff"?"Assign a beautician before starting the service.":params.error==="photo"?"If uploading a Before photo, choose an image up to 4 MB.":params.error==="after-photo"?"If uploading an After photo, choose an image up to 4 MB.":params.error==="recording"?"Confirm that Handy recording has started before starting the service.":params.error==="balance"?"The corrected member price is higher than the available card balance. Recharge the card or enter a lower final price.":"Please check the appointment values."}</div>:null}

    <section className="booking-tools single">
      <form method="get" className="day-picker"><label>View appointment date<input name="date" type="date" defaultValue={date}/></label><button>Show day</button></form>
    </section>

    <details className="admin-booking-create" id="booking" open><summary>+ Appointment details {selectedTime?`· ${selectedTime}`:""}{selectedStaffId>0?` · ${activeStaff.find(person=>Number(person.id)===selectedStaffId)?.full_name??"selected beautician"}`:""}</summary>{selectedTime&&selectedStaffId>0?<div className="selected-slot-banner"><strong>{selectedTime}</strong><span>{new Date(`${date}T00:00:00Z`).toLocaleDateString("en-AU",{day:"numeric",month:"long",timeZone:"UTC"})} · {String(activeStaff.find(person=>Number(person.id)===selectedStaffId)?.full_name??"")}</span><a href={`/admin/calendar?date=${date}`}>Change time</a></div>:null}<form action={createAdminAppointment}><input type="hidden" name="submissionKey" value={submissionKey}/>
      <AppointmentClientPicker showLocation={role==="owner"} initialClient={selectedClient?{id:Number(selectedClient.id),name:String(selectedClient.full_name),mobile:String(selectedClient.mobile),email:String(selectedClient.email??""),clinicLocation:String(selectedClient.clinic_location??"Top Ryde"),membershipStatus:selectedClient.is_premium?"Premium client":"Standard client",visitCount:Number(selectedClient.visit_count??0)}:undefined}/><TreatmentPicker services={activeServices}/><label>Beautician<select name="staffId" defaultValue={selectedStaffId>0?String(selectedStaffId):""}><option value="">Assign later</option>{activeStaff.map(person=><option value={String(person.id)} key={String(person.id)}>{String(person.full_name)}</option>)}</select></label><label>Clinic<select name="clinic" required defaultValue={role==="staff"?"Top Ryde · Shop 3002":""}>{role==="owner"?<option value="" disabled>Select clinic</option>:null}<option>Top Ryde · Shop 3002</option>{role==="owner"?<option>Sydney City · 515 Kent Street</option>:null}</select></label><label>Date<input name="date" type="date" required defaultValue={date}/></label><label>Time<select name="time" required defaultValue={selectedTime}><option value="" disabled>Select time</option>{gridTimes.map(time=><option key={time}>{time}</option>)}</select></label><label className="booking-notes">Notes<textarea name="notes"/></label><label className="booking-check overlap-option"><input type="checkbox" name="allowOverlap" value="yes" defaultChecked={params.overlap==="1"}/> Allow another booking for this beautician at the same time</label><label className="booking-check"><input type="checkbox" name="serviceSmsConsent" value="yes" defaultChecked={Boolean(selectedClient?.service_sms_consent)}/> Client agreed to appointment SMS</label><label className="booking-check"><input type="checkbox" name="marketingSmsConsent" value="yes" defaultChecked={Boolean(selectedClient?.marketing_sms_consent)}/> Client expressly agreed to birthday/marketing SMS</label><button>Create appointment</button></form></details>

    <div className="daily-heading"><div><small>Today / selected date</small><h2>All appointments</h2></div><span>{rows.length} total</span></div>
    <div className="admin-table"><div className="admin-table-head"><span>Time</span><span>Client</span><span>Treatment & clinic</span><span>Status</span><span>Update</span></div>{rows.length?rows.map(row=><div className="booking-admin-row" id={`appointment-${row.id}`} key={String(row.id)}>
      <div><strong>{String(row.requested_time)}</strong><small>{new Date(String(row.requested_date)).toLocaleDateString("en-AU")} · {String(row.source??"website")}</small></div>
      <div><strong>{String(row.full_name)} {role==="owner"?<span className={`clinic-location-badge ${String(row.clinic_location)==="City"?"city":"ryde"}`}>{String(row.clinic_location??"Top Ryde")}</span>:null} {row.is_premium?<span className="premium-client-badge">✦ Premium</span>:null}</strong><small>{String(row.mobile)} · {String(row.email)}</small><a href={`/admin/clients/${row.client_id}`}>Client record →</a></div>
      <div><strong>{String(row.treatment)}</strong><small>{String(row.clinic)} · {row.staff_name?String(row.staff_name):"Unassigned"}</small>{row.started_at?<small>Started {new Date(String(row.started_at)).toLocaleTimeString("en-AU",{hour:"2-digit",minute:"2-digit"})} · Payroll uses clocked hours</small>:null}{row.before_photo_uploaded_at?<a href={`/api/admin/appointments/${row.id}/before-photo`} target="_blank" rel="noreferrer">View Before photo →</a>:null}{row.after_photo_uploaded_at?<a href={`/api/admin/appointments/${row.id}/after-photo`} target="_blank" rel="noreferrer">View After photo →</a>:null}</div>
      <div><span className={`status-pill ${row.status}`}>{statusLabel(row.status)}</span><small>Client: {statusLabel(row.customer_confirmation_status??"pending")} · Deposit: {statusLabel(row.deposit_status)}</small>
        {!["in_progress","completed","cancelled","no_show"].includes(String(row.status))&&row.staff_id?<form action={startAppointmentAction} className="start-service-form"><input type="hidden" name="id" value={String(row.id)}/><input type="hidden" name="staffId" value={String(row.staff_id)}/><input type="hidden" name="returnDate" value={date}/><p>Before starting: confirm Handy recording. A Before photo can be added if needed.</p><label>Before photo (optional)<input name="beforePhoto" type="file" accept="image/*" capture="environment"/></label><label className="booking-check"><input name="handyRecording" type="checkbox" value="yes" required/> I confirm Handy recording has started</label><button type="submit">Start service</button></form>:null}
        {String(row.status)==="in_progress"&&row.staff_id?<form action={finishAppointmentAction} className="finish-service-form"><input type="hidden" name="id" value={String(row.id)}/><input type="hidden" name="staffId" value={String(row.staff_id)}/><input type="hidden" name="returnDate" value={date}/><label>After photo (optional)<input name="afterPhoto" type="file" accept="image/*" capture="environment"/></label><textarea name="comment" required placeholder="Completion comment" aria-label={`Completion comment for ${row.full_name}`}/><button type="submit">End service</button></form>:null}
      </div>
      <div className="booking-update-actions"><form action={changeAppointment}><input type="hidden" name="id" value={String(row.id)}/><select name="staffId" defaultValue={row.staff_id?String(row.staff_id):""} aria-label={`Staff for ${row.full_name}`}><option value="">Unassigned staff</option>{staff.filter(person=>person.active).map(person=><option value={String(person.id)} key={String(person.id)}>{String(person.full_name)}</option>)}</select><select name="status" defaultValue={String(row.status)} aria-label={`Status for ${row.full_name}`}><option value="confirmed">Confirmed</option><option value="in_progress">In progress</option>{String(row.status)==="completed"?<option value="completed">Completed</option>:null}<option value="cancelled">Cancelled</option><option value="no_show">No-show</option></select><select name="depositStatus" defaultValue={String(row.deposit_status)} aria-label={`Deposit for ${row.full_name}`}><option value="unpaid">Deposit unpaid</option><option value="paid">Deposit paid</option><option value="refunded">Refunded</option><option value="forfeited">Forfeited</option><option value="waived">Premium · no deposit</option></select><label>Treatment price (AUD)<input name="totalAmount" type="number" min="0" step="0.01" defaultValue={Number(row.total_amount)} aria-label={`Treatment price for ${row.full_name}`}/></label><button type="submit">Save appointment</button></form>{role==="owner"&&String(row.status)==="cancelled"?<form action={deleteCancelledAppointmentAction} className="delete-cancelled-form"><input type="hidden" name="id" value={String(row.id)}/><input type="hidden" name="returnDate" value={date}/><button type="submit">Delete cancelled appointment</button></form>:null}</div>
    </div>):<div className="empty-admin">No appointments on this date. Website bookings will appear here automatically.</div>}</div>
  </AdminShell>;
}
